#!/usr/bin/python

# Generate a key, self-signed certificate, and certificate request.
# Usage: gencert hostname [hostname...]
#
# When more than one hostname is provided, a SAN (Subject Alternate Name)
# certificate and request are generated.  The first hostname is used as the
# primary CN for the request.
#
# Author: James E. Blair <jeblair@berkeley.edu>  2010-06-18
#         John H. Robinson, IV <jhriv@ucla.edu>  2020-10-20
# With help from this thread:
# http://www.mail-archive.com/openssl-users@openssl.org/msg47641.html

import os,sys,stat,shutil
import argparse
import subprocess
import tempfile

class GencertArgumentParser(argparse.ArgumentParser):
    def error(self, message):
        sys.stderr.write('error: %s\n\n' % message)
        self.print_help()
        sys.exit(1)

OPENSSL_CNF="""
[ req ]
default_bits = %(bits)s
default_md = sha256
distinguished_name = req_distinguished_name
prompt = no
%(req)s

[ req_distinguished_name ]
C=US
ST=California
L=Los Angeles
O=University of California, Los Angeles
OU=UCLA Library Information Systems
%(cn)s

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[ v3_ca ]
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always,issuer:always
basicConstraints = CA:true
subjectAltName = @alt_names

[ alt_names ]
%(alt)s
"""

SAN_REQ = """
x509_extensions = v3_ca # The extentions to add to the self signed cert
req_extensions = v3_req # The extensions to add to a certificate request
"""

def run(args):
    p = subprocess.Popen(
        args,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        close_fds=True
    )
    p.stdin.close()
    while True:
        o = p.stdout.read(1)
        if not o: break
        sys.stdout.write(o)
        sys.stdout.flush()
    r = p.wait()
    if r:
        raise Exception('Error running %s'%args)

if __name__=="__main__":

    parser = GencertArgumentParser(description="Generate an SSL Certificate and CSR")
    parser.add_argument('-d', '--directory', help='Location to write the key/cert/csr')
    parser.add_argument('hostname', nargs='+', help="Hostname to generate the certificate for. Mulitple hostnames may be provided to generate a SAN request.")
    args = parser.parse_args()


    names = args.hostname

    params = dict(req='', dn='', alt='', bits='2048')

    sanfn = ''
    if len(names)>1:
        # SAN
        san_names = ""
        for i,x in enumerate(names):
            san_names += "DNS.%s = %s\n" % (i,x)
        params['req']=SAN_REQ
        params['alt']=san_names
        sanfn = '-san'

    params['cn']='CN=%s'%names[0]

    keyfile = '%s/%s%s.key' % ( ('/etc/pki/tls/private', args.directory ) [args.directory is not None], names[0], sanfn)
    crtfile = '%s/%s%s.cert' % ( ('/etc/pki/tls/certs', args.directory) [args.directory is not None], names[0], sanfn)
    csrfile = '%s/%s%s.csr' % ( ('/etc/pki/tls/certs', args.directory) [args.directory is not None], names[0], sanfn)

    if os.path.exists(crtfile):
        print "Certificate file exists, aborting"
        print "  ", crtfile
        sys.exit(1)

    if os.path.exists(csrfile):
        print "Certificate request file exists, aborting"
        print "  ", csrfile
        sys.exit(1)

    if args.directory is not None:
        if not os.path.exists(args.directory):
            print 'Creating %s' % args.directory
            try:
                os.mkdir(args.directory)
            except OSError as msg:
                print 'error: unable to create %s\n' % args.directory
                print msg
                sys.exit(1)
        elif not os.path.isdir(args.directory):
            print 'error: %s exists and is not a directory\n' % args.directory
            sys.exit(1)

    tmpdir = tempfile.mkdtemp()
    cnffile = '%s/openssl.cnf' % tmpdir
    fh = os.open (cnffile, os.O_RDWR|os.O_CREAT, stat.S_IREAD|stat.S_IWRITE)

    os.write(fh, OPENSSL_CNF%params)
    os.close(fh)

    if os.path.exists(keyfile):
        print "Key file exists, skipping key generation"
    else:
        # Poor python's touch()
        # This prevents a world-readable keyfile race condition
        os.close(
            os.open (keyfile, os.O_CREAT, stat.S_IREAD|stat.S_IWRITE)
        )
        run(['openssl', 'genrsa', '-out', keyfile, params['bits']])
        os.chmod(keyfile, 0400)

    run(['openssl', 'req', '-config', cnffile, '-new', '-nodes', '-key', keyfile, '-out', csrfile])
    run(['openssl', 'req', '-config', cnffile, '-new', '-nodes', '-key', keyfile, '-out', crtfile, '-x509'])
    run(['openssl', 'req', '-in', csrfile, '-text'])

    shutil.rmtree(tmpdir)
